baseURL = "www.example.com"
languageCode = "en-us"
title = "T. Yuan"

[params]
google_analytics_id = ""
google_tag_manager_id = ""
footer = { }

  [params.homepage]
  show_call_box = true
  hide_view_all_services = false

  [params.logo]
  mobile = "images/nervous-stegosaurus.jpg"
  mobile_height = "36px"
  desktop = "images/TY.jpg"
  desktop_height = "70px"
  alt = "Serif"

  [params.homepage_meta_tags]
  meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_og_title = "Hugo Serif Theme"
  meta_og_type = "website"
  meta_og_url = "https://hugo-serif.netlify.app"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
  meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_twitter_card = "summary"
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"

  [params.team]
  summary_large_truncate = 120

[[menu.main]]
weight = 1
name = "About"

[[menu.main]]
name = "Research"
url = "/services/"
weight = 2

[[menu.main]]
name = "Publications"
url = "/about/"
weight = 3

[[menu.main]]
name = "SensorFusion"
url = "lorem-ipsum"
weight = 4

[[menu.main]]
name = "Products"
url = "lorem-ipsum"
weight = 5

[[menu.main]]
name = "Blog"
url = "lorem-ipsum"
weight = 6

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 7

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
