baseURL = "www.example.com"
languageCode = "en-us"
title = "Ting Yuan"

[params]
google_analytics_id = ""
google_tag_manager_id = ""
footer = { }

  [params.homepage]
  show_call_box = true
  hide_view_all_services = false

  [params.logo]
  mobile = "images/thoughtful-squid.jpg"
  mobile_height = "36px"
  desktop = "images/ISIF.jpg"
  desktop_height = "50px"
  alt = "Serif"

  [params.homepage_meta_tags]
  meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_og_title = "Hugo Serif Theme"
  meta_og_type = "website"
  meta_og_url = "https://hugo-serif.netlify.app"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
  meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_twitter_card = "summary"
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"

  [params.team]
  summary_large_truncate = 120

[[menu.main]]
url = "/services/"
weight = 1

[[menu.main]]
identifier = "lorem-ipsum"
name = "lorem-ipsum"
url = "lorem-ipsum"
weight = 0
parent = "lorem-ipsum"
type = "site_menu_item"

[[menu.main]]
name = "Team"
url = "/team/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
